general:
  env_name: SPAEC
  n_repetition: 10
  n_evaluations: 10
  n_timesteps: 40000
  n_eval_freq: 500
  algorithm: trpo

logging:
  wandb_project: "sb3-spge" #"stowAI-rl-basic-training"

environment:
  vessel_shape: [8,5,5]
  yard_shape: [8,5,5]
  num_containers: 200
  group_num: 8
  group_placement: random
  seed: 4307
  time_penalty_coef: 0.002
  num_cranes: 3

hyperparameters:
  gamma: 0.5251808298392981
  learning_rate: 0.004904933379714715
  gae_lambda: 0.9304874052647713
  n_steps: 512
  cg_damping: 0.013636662737693397
  target_kl: 0.005319142931510579
  policy_kwargs:
    activation_fn: relu
    net_arch: 
      pi: [64, 64]
      vf: [64, 64]